# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_cost_mean <- function(dat_smry, s, e) {
    .Call('_cpss_get_cost_mean', PACKAGE = 'cpss', dat_smry, s, e)
}

get_cost_var <- function(dat_smry, s, e) {
    .Call('_cpss_get_cost_var', PACKAGE = 'cpss', dat_smry, s, e)
}

get_cost_meanvar <- function(dat_smry, s, e) {
    .Call('_cpss_get_cost_meanvar', PACKAGE = 'cpss', dat_smry, s, e)
}

get_cost_em <- function(dat_smry, s, e) {
    .Call('_cpss_get_cost_em', PACKAGE = 'cpss', dat_smry, s, e)
}

SN <- function(dat_smry, n, L, d, model) {
    .Call('_cpss_SN', PACKAGE = 'cpss', dat_smry, n, L, d, model)
}

BS <- function(dat_smry, n, L, d, model) {
    .Call('_cpss_BS', PACKAGE = 'cpss', dat_smry, n, L, d, model)
}

WBS <- function(dat_smry, n, L, d, lr_M, model) {
    .Call('_cpss_WBS', PACKAGE = 'cpss', dat_smry, n, L, d, lr_M, model)
}

PELT <- function(dat_smry, n, pen_val, d, K, model) {
    .Call('_cpss_PELT', PACKAGE = 'cpss', dat_smry, n, pen_val, d, K, model)
}

SN_custom <- function(dat_smry, n, L, d, get_cost) {
    .Call('_cpss_SN_custom', PACKAGE = 'cpss', dat_smry, n, L, d, get_cost)
}

BS_custom <- function(dat_smry, n, L, d, get_cost) {
    .Call('_cpss_BS_custom', PACKAGE = 'cpss', dat_smry, n, L, d, get_cost)
}

WBS_custom <- function(dat_smry, n, L, d, lr_M, get_cost) {
    .Call('_cpss_WBS_custom', PACKAGE = 'cpss', dat_smry, n, L, d, lr_M, get_cost)
}

PELT_custom <- function(dat_smry, n, pen_val, d, K, get_cost) {
    .Call('_cpss_PELT_custom', PACKAGE = 'cpss', dat_smry, n, pen_val, d, K, get_cost)
}

lh_binom <- function(N, x) {
    .Call('_cpss_lh_binom', PACKAGE = 'cpss', N, x)
}

lh_multinom <- function(N, x) {
    .Call('_cpss_lh_multinom', PACKAGE = 'cpss', N, x)
}

est_cov <- function(dataset) {
    .Call('_cpss_est_cov', PACKAGE = 'cpss', dataset)
}

g_smry_mean <- function(dataset, Sigma) {
    .Call('_cpss_g_smry_mean', PACKAGE = 'cpss', dataset, Sigma)
}

g_smry_var <- function(dataset, mu) {
    .Call('_cpss_g_smry_var', PACKAGE = 'cpss', dataset, mu)
}

g_smry_meanvar <- function(dataset, param_opt) {
    .Call('_cpss_g_smry_meanvar', PACKAGE = 'cpss', dataset, param_opt)
}

g_smry_em <- function(dataset, param_opt) {
    .Call('_cpss_g_smry_em', PACKAGE = 'cpss', dataset, param_opt)
}

